AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 我的现有项目 SAM 配置

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  # API Gateway + Lambda 函数
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./              # 当前目录所有代码
      Handler: src/app.handler # 你的入口文件和处理函数
      Events:
        # 捕获所有 HTTP 请求
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"